excluded:
  - Pods
  - ChronicleSync Tests

disabled_rules:
  - trailing_whitespace
  - line_length
  - function_body_length
  - type_body_length
  - file_length

opt_in_rules:
  - empty_count
  - empty_string
  - force_unwrapping
  - private_outlet
  - unneeded_parentheses_in_closure_argument

identifier_name:
  min_length: 2
  excluded:
    - id
    - URL
    - url

type_name:
  min_length: 3
  max_length: 50

reporter: "xcode"