name = "chroniclesync-setup"
main = "src/index.js"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "staging"
database_name = "chronicle-db"
database_id = "c353cc76-f5cd-41d0-bd9a-9b4629ab4d14"

[[d1_databases]]
binding = "production"
database_name = "chronicle-db"
database_id = "00e393b1-4339-4fcf-9612-8ae11274ff3d"
