name: ChronicleSync
options:
  bundleIdPrefix: com.chroniclesync
  deploymentTarget:
    iOS: 14.0

targets:
  ChronicleSync:
    type: application
    platform: iOS
    deploymentTarget: "14.0"
    sources: [ChronicleSync]
    info:
      path: ChronicleSync/Info.plist
      properties:
        CFBundleDisplayName: ChronicleSync
        UILaunchStoryboardName: LaunchScreen
    dependencies:
      - target: Extension
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.chroniclesync.app
        
  Extension:
    type: app-extension
    platform: iOS
    deploymentTarget: "14.0"
    sources: [Extension]
    info:
      path: Extension/Info.plist
      properties:
        NSExtension:
          NSExtensionPointIdentifier: com.apple.Safari.web-extension
          NSExtensionPrincipalClass: $(PRODUCT_MODULE_NAME).SafariWebExtensionHandler
    settings:
      base:
        INFOPLIST_FILE: Extension/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.chroniclesync.extension
        
  ExtensionTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "14.0"
    sources: [Extension/Tests]
    dependencies:
      - target: Extension
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.chroniclesync.extension.tests
        INFOPLIST_FILE: Extension/Tests/Info.plist

schemes:
  ChronicleSync:
    build:
      targets:
        ChronicleSync: all
        Extension: all
        ExtensionTests: [test]
    test:
      targets:
        - ExtensionTests
      gatherCoverageData: true
      coverageTargets:
        - Extension
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
