name: Chrome Extension CI/CD

on:
  push:
    branches: [main]
    paths:
      - 'extension/**'
      - '.github/workflows/chrome-extension.yml'
  pull_request:
    branches: [main]
    paths:
      - 'extension/**'
      - '.github/workflows/chrome-extension.yml'
  workflow_dispatch:
    inputs:
      api_endpoint:
        description: 'API endpoint to test against'
        required: false
        type: string
        default: 'https://api-staging.chroniclesync.xyz'
      debug:
        description: 'Enable debug mode'
        required: false
        type: boolean
        default: false

env:
  NODE_VERSION: '20'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'staging' }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: |
            extension/package-lock.json

      - name: Build Chrome Extension
        working-directory: extension
        run: |
          npm ci
          npm run build:chrome

      - name: Upload Extension Artifact
        uses: actions/upload-artifact@v4
        with:
          name: chrome-extension
          path: extension/chrome-extension.zip
          retention-days: 14

      - name: Test Extension
        working-directory: extension
        run: |
          npm run lint
          npm run test

      - name: Install dependencies and run e2e tests
        working-directory: extension
        env:
          API_URL: ${{ github.event.inputs.api_endpoint || (github.ref == 'refs/heads/main' && 'https://api.chroniclesync.xyz' || 'https://api-staging.chroniclesync.xyz') }}
          DEBUG: ${{ github.event.inputs.debug && 'pw:api' || '' }}
          PWDEBUG: ${{ github.event.inputs.debug && '1' || '' }}
        run: |
          npm ci
          npx playwright install --with-deps chromium
          npm run test:e2e:chrome

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-reports-chrome
          path: |
            extension/playwright-report/
            extension/test-results/
          retention-days: 30