name: E2E Tests

on:
  workflow_run:
    workflows: ["Deploy to Staging"]
    types:
      - completed

jobs:
  e2e-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: pages/package-lock.json
      
      - name: Install dependencies
        working-directory: pages
        run: npm ci
      
      - name: Install Playwright browsers
        working-directory: pages
        run: npx playwright install chromium --with-deps
      
      - name: Run Playwright tests
        working-directory: pages
        run: npm run test:e2e
        env:
          CI: true
      
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: |
            pages/test-results/
            pages/playwright-report/
          retention-days: 30