name: iOS Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  ios-build-and-test:
    name: Build and Test iOS Safari Extension
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      
      - name: Install dependencies
        run: |
          gem install xcpretty
          brew install swiftlint
      
      - name: Copy extension resources
        run: |
          mkdir -p ChronicleSync/ChronicleSync\ Extension/Resources
          cp extension/src/background.ts ChronicleSync/ChronicleSync\ Extension/Resources/background.js
          cp extension/src/content-script.ts ChronicleSync/ChronicleSync\ Extension/Resources/content-script.js
          cp extension/popup.html ChronicleSync/ChronicleSync\ Extension/Resources/
          cp extension/popup.css ChronicleSync/ChronicleSync\ Extension/Resources/
          cp extension/src/popup.tsx ChronicleSync/ChronicleSync\ Extension/Resources/popup.js
          cp extension/manifest.json ChronicleSync/ChronicleSync\ Extension/Resources/
      
      - name: Run SwiftLint
        run: swiftlint --strict
      
      - name: Build iOS App
        run: |
          xcodebuild clean build test \
            -project ChronicleSync/ChronicleSync.xcodeproj \
            -scheme "ChronicleSync" \
            -sdk iphonesimulator \
            -destination "platform=iOS Simulator,name=iPhone 14,OS=latest" \
            -enableCodeCoverage YES | xcpretty
      
      - name: Archive iOS App
        if: github.ref == 'refs/heads/main'
        run: |
          xcodebuild archive \
            -project ChronicleSync/ChronicleSync.xcodeproj \
            -scheme "ChronicleSync" \
            -archivePath ChronicleSync/build/ChronicleSync.xcarchive \
            -sdk iphoneos \
            -configuration Release | xcpretty
      
      - name: Upload iOS App Artifact
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: ios-app
          path: ChronicleSync/build/ChronicleSync.xcarchive
          retention-days: 14
      
      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ios-test-results
          path: |
            ChronicleSync/build/reports
            ChronicleSync/build/logs
          retention-days: 30