name: iOS Build

on:
  push:
    branches: [ main, ios-extension-* ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install Node.js dependencies
      run: |
        cd shared
        npm install
        npm run build:ios
    
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    
    - name: Build iOS app
      run: |
        cd ChronicleSync-iOS
        xcodebuild -project ChronicleSync-iOS.xcodeproj -scheme ChronicleSync-iOS -destination 'platform=iOS Simulator,name=iPhone 14' build