name: iOS Build and Test

on:
  push:
    branches: [main]
    paths:
      - 'ios/**'
      - 'extension/**'
      - '.github/workflows/ios-build.yml'
  pull_request:
    branches: [main]
    paths:
      - 'ios/**'
      - 'extension/**'
      - '.github/workflows/ios-build.yml'
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: macos-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: |
            extension/package-lock.json
      
      - name: Install Chrome Extension Dependencies
        working-directory: extension
        run: npm ci
      
      - name: Build Chrome Extension
        working-directory: extension
        run: npm run build
      
      - name: Make Safari Extension Build Script Executable
        run: chmod +x ios/build-safari-extension.sh
      
      - name: Build Safari Extension
        working-directory: ios
        run: ./build-safari-extension.sh
      
      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      
      - name: Install xcpretty
        run: gem install xcpretty
      
      - name: Build iOS App
        working-directory: ios
        run: |
          xcodebuild clean build test \
            -project ChronicleSync/ChronicleSync.xcodeproj \
            -scheme ChronicleSync \
            -destination 'platform=iOS Simulator,name=iPhone 15' \
            -sdk iphonesimulator \
            CODE_SIGNING_ALLOWED=NO \
            | xcpretty
      
      - name: Run iOS Tests
        working-directory: ios
        run: |
          xcodebuild test \
            -project ChronicleSync/ChronicleSync.xcodeproj \
            -scheme "ChronicleSync Tests" \
            -destination 'platform=iOS Simulator,name=iPhone 15' \
            -sdk iphonesimulator \
            CODE_SIGNING_ALLOWED=NO \
            | xcpretty
      
      - name: Create Unsigned IPA
        working-directory: ios
        run: |
          # Build for generic iOS device
          xcodebuild clean archive \
            -project ChronicleSync/ChronicleSync.xcodeproj \
            -scheme ChronicleSync \
            -archivePath build/ChronicleSync.xcarchive \
            -sdk iphoneos \
            -destination 'generic/platform=iOS' \
            CODE_SIGNING_ALLOWED=NO \
            | xcpretty
          
          # Create IPA from archive
          mkdir -p build/Payload
          cp -r build/ChronicleSync.xcarchive/Products/Applications/ChronicleSync.app build/Payload/
          cd build && zip -r ChronicleSync.ipa Payload
      
      - name: Upload Unsigned IPA
        uses: actions/upload-artifact@v4
        with:
          name: ChronicleSync-Unsigned-IPA
          path: ios/build/ChronicleSync.ipa
          retention-days: 7