name: iOS Tests

on:
  push:
    branches: [main]
    paths:
      - 'extension/**'
  pull_request:
    branches: [main]
    paths:
      - 'extension/**'
  workflow_dispatch:

jobs:
  build-and-test-ios:
    name: Build and Test iOS
    runs-on: macos-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      
      - name: Install dependencies
        run: |
          cd extension
          npm ci
          npm run build
      
      - name: Build Safari extension
        run: |
          cd extension
          NODE_OPTIONS="--experimental-vm-modules --no-warnings" npm run build:extension
      
      - name: List available simulators
        run: |
          xcrun simctl list devices available

      - name: Build and test iOS app
        run: |
          cd extension/ios-tests/ChronicleSync
          
          # Try specific iPhone 16 Pro simulator first
          if xcodebuild build test -scheme "ChronicleSync" -destination "platform=iOS Simulator,OS=18.2,name=iPhone 16 Pro" -resultBundlePath TestResults.xcresult; then
            echo "Successfully built and tested with iPhone 16 Pro simulator"
          else
            echo "Failed with specific simulator, trying fallback options"
            
            # Find an available simulator
            SIMULATOR_ID=$(xcrun simctl list devices available -j | jq -r '.devices | to_entries[] | .value[] | select(.isAvailable == true and (.name | contains("iPhone"))) | .udid' | head -n 1)
            
            if [ -z "$SIMULATOR_ID" ]; then
              echo "No available iPhone simulator found, trying any simulator"
              SIMULATOR_ID=$(xcrun simctl list devices available -j | jq -r '.devices | to_entries[] | .value[] | select(.isAvailable == true) | .udid' | head -n 1)
            fi
            
            if [ -z "$SIMULATOR_ID" ]; then
              echo "No available simulator found, using generic destination"
              xcodebuild build test -scheme "ChronicleSync" -destination "platform=iOS Simulator,id=dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder" -resultBundlePath TestResults.xcresult
            else
              echo "Using simulator with ID: $SIMULATOR_ID"
              xcodebuild build test -scheme "ChronicleSync" -destination "platform=iOS Simulator,id=$SIMULATOR_ID" -resultBundlePath TestResults.xcresult
            fi
          fi
      
      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ios-test-results
          path: extension/ios-tests/ChronicleSync/TestResults.xcresult
          retention-days: 30
      
      - name: Extract screenshots
        if: always()
        run: |
          cd extension/ios-tests/ChronicleSync
          mkdir -p screenshots
          xcrun xcresulttool get --path TestResults.xcresult --format json | grep -o '"filename" : ".*\.png"' | awk -F'"' '{print $4}' | xargs -I{} find TestResults.xcresult -name {} -exec cp {} screenshots/ \;
      
      - name: Upload screenshots
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ios-screenshots
          path: extension/ios-tests/ChronicleSync/screenshots
          retention-days: 30