name: Playwright Tests

on:
  workflow_dispatch:
    inputs:
      browser:
        description: 'Browser to test'
        required: true
        default: 'chromium'
        type: choice
        options:
          - chromium
          - firefox
          - webkit
      api_endpoint:
        description: 'API endpoint to test against'
        required: false
        type: string
        default: 'https://api-staging.chroniclesync.xyz'
      debug:
        description: 'Enable debug mode'
        required: false
        type: boolean
        default: false

env:
  NODE_VERSION: '18'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: pages/package-lock.json

      - name: Install dependencies
        working-directory: pages
        run: |
          npm ci
          npx playwright install --with-deps ${{ inputs.browser }}

      - name: Build extension
        working-directory: pages
        env:
          API_URL: ${{ inputs.api_endpoint }}
        run: npm run build:extension

      - name: Run Playwright tests
        working-directory: pages
        env:
          DEBUG: ${{ inputs.debug && 'pw:api' || '' }}
          PWDEBUG: ${{ inputs.debug && '1' || '' }}
        run: |
          xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" \
            npx playwright test --project=${{ inputs.browser }}

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-${{ inputs.browser }}
          path: |
            pages/playwright-report/
            pages/test-results/
          retention-days: 30