name: Build Safari Extension

on:
  push:
    branches: [main]
    paths-ignore:
      - 'pages/**'
  pull_request:
    branches: [main]
    paths-ignore:
      - 'pages/**'
  workflow_dispatch:
    inputs:
      debug:
        description: 'Enable debug mode'
        required: false
        type: boolean
        default: false

env:
  NODE_VERSION: '20'
  XCODE_VERSION: '15.2'
  APP_NAME: 'ChronicleSync'
  BUNDLE_ID: 'xyz.chroniclesync.safari-extension'
  
# These secrets are expected to be set in the GitHub repository:
# APPLE_TEAM_ID: The Apple Developer Team ID
# APPLE_CERTIFICATE_CONTENT: Base64-encoded Apple Developer certificate
# APPLE_CERTIFICATE_PASSWORD: Password for the certificate
# APPLE_PROVISIONING_PROFILE: Base64-encoded provisioning profile
# APPLE_API_KEY_ID: App Store Connect API Key ID
# APPLE_API_ISSUER_ID: App Store Connect API Issuer ID
# APPLE_API_KEY_CONTENT: App Store Connect API Key content
# APPLE_APP_ID: The App ID in App Store Connect

jobs:
  build-safari-extension:
    name: Build Safari Extension
    runs-on: macos-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'staging' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: |
            extension/package-lock.json

      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode_${{ env.XCODE_VERSION }}.app

      - name: Build Extension
        working-directory: extension
        run: |
          npm ci
          npm run build

      - name: Create iOS App Project
        run: |
          # Create a new iOS app project with Safari extension capability
          mkdir -p ios-app
          cd ios-app
          
          # Create Swift project structure
          mkdir -p ${{ env.APP_NAME }}
          mkdir -p ${{ env.APP_NAME }}/Resources
          mkdir -p ${{ env.APP_NAME }}/Extension
          
          # Create main app Info.plist from template
          sed 's/{{APP_NAME}}/${{ env.APP_NAME }}/g' ../.github/templates/Info.plist.template > ${{ env.APP_NAME }}/Info.plist
          
          # Create extension Info.plist from template
          sed 's/{{APP_NAME}}/${{ env.APP_NAME }}/g' ../.github/templates/Extension-Info.plist.template > ${{ env.APP_NAME }}/Extension/Info.plist
          
          # Copy Swift files from templates
          cp ../.github/templates/AppDelegate.swift.template ${{ env.APP_NAME }}/AppDelegate.swift
          cp ../.github/templates/ViewController.swift.template ${{ env.APP_NAME }}/ViewController.swift
          cp ../.github/templates/SafariWebExtensionHandler.swift.template ${{ env.APP_NAME }}/Extension/SafariWebExtensionHandler.swift
          cp ../.github/templates/LaunchScreen.storyboard.template ${{ env.APP_NAME }}/LaunchScreen.storyboard
          
          # Create project.pbxproj (simplified version)
          mkdir -p ${{ env.APP_NAME }}.xcodeproj
          cat > ${{ env.APP_NAME }}.xcodeproj/project.pbxproj << EOF
          // !$*UTF8*$!
          {
            archiveVersion = 1;
            classes = {};
            objectVersion = 56;
            rootObject = 83CBB9F71A601CBA00E9B192;
          }
          EOF

      - name: Copy Extension Resources
        run: |
          # Copy the built extension files to the Safari extension directory
          mkdir -p ios-app/${{ env.APP_NAME }}/Extension/Resources
          cp -r extension/dist/* ios-app/${{ env.APP_NAME }}/Extension/Resources/
          cp extension/manifest.json ios-app/${{ env.APP_NAME }}/Extension/Resources/
          cp extension/popup.html extension/popup.css ios-app/${{ env.APP_NAME }}/Extension/Resources/
          cp extension/settings.html extension/settings.css ios-app/${{ env.APP_NAME }}/Extension/Resources/
          cp extension/history.html extension/history.css ios-app/${{ env.APP_NAME }}/Extension/Resources/
          cp extension/devtools.html extension/devtools.css ios-app/${{ env.APP_NAME }}/Extension/Resources/
          cp extension/bip39-wordlist.js ios-app/${{ env.APP_NAME }}/Extension/Resources/

      - name: Create Xcode Configuration
        env:
          TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
        run: |
          # Create xcconfig file with secrets
          cat > ios-app/${{ env.APP_NAME }}.xcconfig << EOF
          DEVELOPMENT_TEAM = ${TEAM_ID}
          PRODUCT_BUNDLE_IDENTIFIER = ${{ env.BUNDLE_ID }}
          PRODUCT_BUNDLE_IDENTIFIER_EXTENSION = ${{ env.BUNDLE_ID }}.Extension
          CODE_SIGN_STYLE = Automatic
          CODE_SIGN_IDENTITY = Apple Development
          IPHONEOS_DEPLOYMENT_TARGET = 15.0
          TARGETED_DEVICE_FAMILY = 1,2
          SWIFT_VERSION = 5.0
          ENABLE_BITCODE = NO
          EOF

      - name: Build iOS App with Safari Extension
        env:
          TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
        run: |
          cd ios-app
          
          # Create a simple Xcode project using Swift Package Manager
          cat > Package.swift << EOF
          // swift-tools-version:5.5
          import PackageDescription

          let package = Package(
              name: "${{ env.APP_NAME }}",
              platforms: [.iOS(.v15)],
              products: [
                  .library(name: "${{ env.APP_NAME }}", targets: ["${{ env.APP_NAME }}"]),
                  .library(name: "${{ env.APP_NAME }}Extension", targets: ["${{ env.APP_NAME }}Extension"])
              ],
              targets: [
                  .target(name: "${{ env.APP_NAME }}"),
                  .target(name: "${{ env.APP_NAME }}Extension")
              ]
          )
          EOF
          
          # Create build script from template
          sed -e 's/{{APP_NAME}}/${{ env.APP_NAME }}/g' \
              -e 's/{{BUNDLE_ID}}/${{ env.BUNDLE_ID }}/g' \
              -e 's/{{TEAM_ID}}/$TEAM_ID/g' \
              ../.github/templates/build-ios-app.sh.template > build-ios-app.sh
          
          # Create export options plist from template
          sed -e 's/{{TEAM_ID}}/$TEAM_ID/g' \
              -e 's/{{BUNDLE_ID}}/${{ env.BUNDLE_ID }}/g' \
              ../.github/templates/exportOptions.plist.template > exportOptions.plist
          
          # Make build script executable
          chmod +x build-ios-app.sh
          
          # Run the build script
          ./build-ios-app.sh

      - name: Create IPA File
        run: |
          cd ios-app
          
          # If the build script didn't create an IPA, create one manually
          if [ ! -f "build/${{ env.APP_NAME }}.ipa" ]; then
            mkdir -p Payload
            cp -r build/${{ env.APP_NAME }}.xcarchive/Products/Applications/${{ env.APP_NAME }}.app Payload/
            zip -r ${{ env.APP_NAME }}.ipa Payload
            rm -rf Payload
          else
            cp build/${{ env.APP_NAME }}.ipa ./${{ env.APP_NAME }}.ipa
          fi

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: safari-extension-ipa
          path: ios-app/${{ env.APP_NAME }}.ipa
          retention-days: 14

      - name: Upload Safari Extension Artifact
        uses: actions/upload-artifact@v4
        with:
          name: safari-extension-resources
          path: ios-app/${{ env.APP_NAME }}/Extension/Resources
          retention-days: 14

      - name: Prepare for TestFlight
        if: github.ref == 'refs/heads/main' && success()
        env:
          APPLE_API_KEY_ID: ${{ secrets.APPLE_API_KEY_ID }}
          APPLE_API_ISSUER_ID: ${{ secrets.APPLE_API_ISSUER_ID }}
          APPLE_API_KEY_CONTENT: ${{ secrets.APPLE_API_KEY_CONTENT }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          APPLE_APP_ID: ${{ secrets.APPLE_APP_ID }}
          APPLE_CERTIFICATE_CONTENT: ${{ secrets.APPLE_CERTIFICATE_CONTENT }}
          APPLE_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
          APPLE_PROVISIONING_PROFILE: ${{ secrets.APPLE_PROVISIONING_PROFILE }}
        run: |
          # Create temporary files for credentials
          echo "$APPLE_API_KEY_CONTENT" > apple_api_key.p8
          
          # Set up certificate and provisioning profile if provided
          if [ ! -z "$APPLE_CERTIFICATE_CONTENT" ] && [ ! -z "$APPLE_PROVISIONING_PROFILE" ]; then
            echo "Setting up certificate and provisioning profile..."
            
            # Create keychain
            KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db
            KEYCHAIN_PASSWORD="temporary-password"
            security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
            security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
            security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
            
            # Import certificate
            echo "$APPLE_CERTIFICATE_CONTENT" | base64 --decode > certificate.p12
            security import certificate.p12 -P "$APPLE_CERTIFICATE_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
            security list-keychain -d user -s $KEYCHAIN_PATH
            
            # Set up provisioning profile
            mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
            echo "$APPLE_PROVISIONING_PROFILE" | base64 --decode > provisioning_profile.mobileprovision
            cp provisioning_profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/
          fi
          
          # Validate the IPA file
          xcrun altool --validate-app \
            -f ios-app/${{ env.APP_NAME }}.ipa \
            -t ios \
            -k apple_api_key.p8 \
            -u $APPLE_API_KEY_ID \
            -p $APPLE_API_ISSUER_ID || true
          
          # Log validation information
          echo "Safari extension IPA is ready for TestFlight"
          echo "Bundle ID: ${{ env.BUNDLE_ID }}"
          echo "Team ID: $APPLE_TEAM_ID"
          echo "App ID: $APPLE_APP_ID"
          
          # Clean up
          rm -f apple_api_key.p8 certificate.p12 provisioning_profile.mobileprovision