name: Safari Extension CI/CD

on:
  push:
    branches: [main]
    paths:
      - 'extension/**'
      - '.github/workflows/safari-extension.yml'
  pull_request:
    branches: [main]
    paths:
      - 'extension/**'
      - '.github/workflows/safari-extension.yml'
  workflow_dispatch:
    inputs:
      api_endpoint:
        description: 'API endpoint to test against'
        required: false
        type: string
        default: 'https://api-staging.chroniclesync.xyz'
      debug:
        description: 'Enable debug mode'
        required: false
        type: boolean
        default: false

env:
  NODE_VERSION: '20'

jobs:
  build-and-test:
    runs-on: macos-latest  # Use macOS runner for Safari/iOS testing
    environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'staging' }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: |
            extension/package-lock.json

      - name: Build Safari Extension
        working-directory: extension
        run: |
          npm ci
          npm run build:safari

      - name: Upload Extension Artifact
        uses: actions/upload-artifact@v4
        with:
          name: safari-extension
          path: extension/safari-extension.zip
          retention-days: 14

      - name: Test Extension
        working-directory: extension
        run: |
          npm run lint
          npm run test

      - name: Install dependencies and run e2e tests
        working-directory: extension
        env:
          API_URL: ${{ github.event.inputs.api_endpoint || (github.ref == 'refs/heads/main' && 'https://api.chroniclesync.xyz' || 'https://api-staging.chroniclesync.xyz') }}
          DEBUG: ${{ github.event.inputs.debug && 'pw:api' || '' }}
          PWDEBUG: ${{ github.event.inputs.debug && '1' || '' }}
        run: |
          npm ci
          npx playwright install --with-deps webkit
          
          # For Safari iOS testing, we would use Appium with XCUITest driver
          # This is a placeholder for the actual iOS testing setup
          # In a real implementation, you would:
          # 1. Install and configure Appium
          # 2. Set up iOS simulators
          # 3. Build the Safari extension for iOS
          # 4. Run tests on iOS simulators
          
          # For now, we'll run the tests on WebKit (desktop Safari)
          npm run test:e2e:webkit

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-reports-safari
          path: |
            extension/playwright-report/
            extension/test-results/
          retention-days: 30