name: Safari Extension UI Tests

on:
  push:
    branches: [ main, add-github-actions-workflow ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Safari Extension UI Tests
    runs-on: macos-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      
      - name: Install dependencies
        run: |
          cd extension
          npm install
      
      - name: Build Safari Extension
        run: |
          cd extension/ChronicleSync
          xcodebuild -project ChronicleSync.xcodeproj -scheme "ChronicleSync (iOS)" -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 14,OS=latest" build
      
      - name: Start Backend Server
        run: |
          cd extension
          npm run start-test-server &
          sleep 10 # Wait for server to start
      
      - name: Run UI Tests
        run: |
          cd extension/ChronicleSync
          xcodebuild test -project ChronicleSync.xcodeproj -scheme "ChronicleSync-UITests" -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 14,OS=latest" -resultBundlePath TestResults
      
      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: extension/ChronicleSync/TestResults