name: Test Safari IPA in Simulator

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    paths:
      - 'extension/scripts/build-safari-extension.cjs'
      - 'extension/scripts/improved-safari-extension.cjs'
      - 'extension/scripts/create-test-ipa.js'
      - 'extension/scripts/test-ipa-in-simulator.js'
      - '.github/workflows/test-safari-ipa.yml'

jobs:
  build-safari-ipa:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: extension/package-lock.json
      
      - name: Install dependencies
        working-directory: extension
        run: npm ci
      
      - name: Generate Safari IPA
        working-directory: extension
        run: |
          # Try to generate Safari IPA file using the improved script first
          NODE_OPTIONS="--experimental-vm-modules --no-warnings" npm run build:safari-ipa:improved || {
            echo "Safari IPA generation failed, creating a test IPA using our script"
            npm run create:test-ipa
          }
          
          # List the generated IPA file
          ls -la ipa-output/*.ipa
      
      - name: Upload Safari IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: safari-extension-ipa
          path: extension/ipa-output/*.ipa
          retention-days: 14
  
  test-safari-ipa:
    needs: build-safari-ipa
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: extension/package-lock.json
      
      - name: Install dependencies
        working-directory: extension
        run: npm ci
      
      - name: Download Safari IPA artifact
        uses: actions/download-artifact@v4
        with:
          name: safari-extension-ipa
          path: ./extension/ipa-output
          
      - name: List downloaded IPA files
        run: |
          ls -la ./extension/ipa-output
          
      - name: Test IPA in simulator
        working-directory: extension
        run: |
          npm run test:ipa-in-simulator
          
      - name: Upload simulator screenshots
        uses: actions/upload-artifact@v4
        with:
          name: safari-app-screenshots
          path: extension/simulator-screenshots/*.png
          retention-days: 14